import {DEFAULT_SETTINGS,PRESETS,loadSettings,saveSettings,type LinkPeekSettings} from "../shared/settings";
let s:LinkPeekSettings=DEFAULT_SETTINGS;let host="";
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
(async()=>{s=await loadSettings();$("enabled").toggleAttribute("checked",s.enabled);($("enabled") as HTMLInputElement).checked=s.enabled;($("preset") as HTMLSelectElement).value=s.preset;
  const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(tab?.url?.startsWith("http")){host=new URL(tab.url).hostname;$("site").textContent=host}else $("site").textContent="Not a web page";
})();
$("enabled").addEventListener("change",async e=>{s.enabled=(e.target as HTMLInputElement).checked;await saveSettings(s)});
$("preset").addEventListener("change",async e=>{const p=(e.target as HTMLSelectElement).value;s={...s,...(PRESETS[p]??{}),preset:p as LinkPeekSettings["preset"]};await saveSettings(s)});
$("options").addEventListener("click",()=>chrome.runtime.openOptionsPage());
$("help").addEventListener("click",()=>chrome.tabs.create({url:chrome.runtime.getURL("onboarding.html")}));
$("clear").addEventListener("click",async()=>{await chrome.runtime.sendMessage({type:"LINKPEEK_CLEAR_CACHE"});$("clear").textContent="Cleared"});
$("disableSite").addEventListener("click",async()=>{if(!host)return;const cur=s.siteProfiles[host]??{};s.siteProfiles={...s.siteProfiles,[host]:{...cur,enabled:cur.enabled===false?true:false}};await saveSettings(s);$("disableSite").textContent=s.siteProfiles[host].enabled===false?"Enable site":"Disable site"});
